# -*- coding: utf-8 -*-
"""Another copy of model with recommendations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zpn3_Zce3ti8-CtOpBha-MoKgUKr1jGV
"""

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf

model_path = "/content/drive/MyDrive/stacked_model.keras"  # Update with the correct path
model = tf.keras.models.load_model(model_path)

print("Model loaded successfully!")

from tensorflow.keras.preprocessing import image
import numpy as np

def preprocess_image(img_path):
    img = image.load_img(img_path, target_size=(224, 224))  # Adjust based on your model
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array /= 255.0  # Normalize if needed
    return img_array

from google.colab import files

uploaded = files.upload()  # Upload an image from your computer

# Get the uploaded image file name
img_path = list(uploaded.keys())[0]
processed_img = preprocess_image(img_path)

# Predict
predictions = model.predict(processed_img)
predicted_class = np.argmax(predictions)

print(f"Predicted Class Index: {predicted_class}")

import matplotlib.pyplot as plt
import cv2
import os
image = cv2.imread(img_path)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)  # Convert from BGR to RGB

# Display the image
plt.figure(figsize=(6,6))
plt.imshow(image)
plt.axis('off')  # Hide axis
plt.title("Uploaded Image")
plt.show()

import json

labels_path = "/content/drive/MyDrive/class_labels.json"  # Update with the correct path
with open(labels_path, "r") as f:
    class_labels = json.load(f)

predicted_label = class_labels[predicted_class]
print(f"Predicted Label: {predicted_label}")

import pandas as pd
df=pd.read_csv("/content/medicinal_uses(2).csv",encoding="ISO-8859-1")

data=df.iloc[predicted_class]
print(data)

data=df.iloc[predicted_class]['Utilities']
print("UTILITIES:")
print(data)
Remedy=df.iloc[predicted_class]['Remedies']
print("REMEDIES:")
print(Remedy)

Remedy=df.iloc[predicted_class]['Remedies']
print("remedies:")
print(Remedy)

