# -*- coding: utf-8 -*-
"""Another copy of Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5MKyDpSbveUC5PbCgOf2TgyT1D_q_RW
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import InceptionV3, ConvNeXtTiny
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D, Input, concatenate
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping
import os
import zipfile
from google.colab import drive
drive.mount('/content/drive')

with zipfile.ZipFile('/content/drive/MyDrive/Medicinal Leaf Dataset.zip','r') as zip_ref:
  zip_ref.extractall('dataset')
extracted_files=os.listdir('dataset')
print(extracted_files)

data_dir='dataset/Medicinal Leaf Dataset/Segmented Medicinal Leaf Images'
IMG_HEIGHT, IMG_WIDTH = 224, 224
BATCH_SIZE = 32

# Data Augmentation
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest',
    validation_split=0.2
)

validation_datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)

train_generator = train_datagen.flow_from_directory(
    data_dir, target_size=(IMG_HEIGHT, IMG_WIDTH), batch_size=BATCH_SIZE,
    class_mode='categorical', subset='training'
)

validation_generator = validation_datagen.flow_from_directory(
    data_dir, target_size=(IMG_HEIGHT, IMG_WIDTH), batch_size=BATCH_SIZE,
    class_mode='categorical', subset='validation'
)

# Function to create base model
def create_base_model(model_class):
    base_model = model_class(weights='imagenet', include_top=False, input_shape=(IMG_HEIGHT, IMG_WIDTH, 3))

    # Unfreeze top 20 layers for fine-tuning
    for layer in base_model.layers[-20:]:
        layer.trainable = True

    x = GlobalAveragePooling2D()(base_model.output)
    x = Dense(512, activation='relu')(x)
    x = Dropout(0.3)(x)
    predictions = Dense(train_generator.num_classes, activation='softmax')(x)

    model = Model(inputs=base_model.input, outputs=predictions)
    model.compile(optimizer=Adam(learning_rate=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])

    return model

models = [create_base_model(InceptionV3), create_base_model(ConvNeXtTiny)]

# Train models
for model in models:
    model.fit(
        train_generator,
        validation_data=validation_generator,
        epochs=20,
        callbacks=[
            ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2),
            EarlyStopping(monitor='val_accuracy', patience=3, restore_best_weights=True)
        ],
        verbose=1
    )

import tensorflow as tf
from tensorflow.keras.layers import Dense, Dropout, Input, BatchNormalization, Concatenate
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import AdamW
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping

# ✅ Optimized Stacked Model (Fixed Learning Issues)
def create_stacked_model(models):
    inputs = Input(shape=(IMG_HEIGHT, IMG_WIDTH, 3))

    # 🚀 Directly use model outputs without GlobalAveragePooling2D()
    features1 = models[0](inputs, training=False)  # InceptionV3
    features2 = models[1](inputs, training=False)  # ConvNeXt-Tiny

    # ✅ Feature Fusion via Concatenation
    merged_features = Concatenate()([features1, features2])

    # Fully Connected Layers (Slightly Larger to Retain Features)
    x = Dense(384, activation='relu')(merged_features)  # Increased Dense Layer (256 → 384)
    x = BatchNormalization()(x)
    x = Dropout(0.05)(x)  # Reduced Dropout (0.1 → 0.05)
    x = Dense(train_generator.num_classes, activation='softmax')(x)

    # ✅ Cosine Decay with Warm Restarts (Fixes Learning Rate Issue)
    lr_schedule = tf.keras.optimizers.schedules.CosineDecayRestarts(
        initial_learning_rate=0.0002,
        first_decay_steps=8 * len(train_generator),
        t_mul=2.0,
        m_mul=0.8,
        alpha=0.0001  # Prevent LR from becoming too small
    )

    # ✅ AdamW Optimizer with Label Smoothing (Fixes Overconfidence)
    model.compile(
        optimizer=AdamW(learning_rate=lr_schedule, weight_decay=1e-4),
        loss=tf.keras.losses.CategoricalCrossentropy(label_smoothing=0.15),  # Increased Label Smoothing
        metrics=['accuracy']
    )

    return model

# ✅ Create and Train Stacked Model
stacked_model = create_stacked_model(models)

stacked_model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=25,  # Allow more fine-tuning
    batch_size=64,
    callbacks=[
        ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3),
        EarlyStopping(monitor='val_accuracy', patience=8, restore_best_weights=True)  # Increased patience
    ],
    verbose=1
)

# Evaluate the stacked model
stacked_accuracy = stacked_model.evaluate(validation_generator)[1]
print(f'Stacked Model Validation Accuracy: {stacked_accuracy * 100:.2f}%')